services:
  #  redis for bullmq
  queuedb:
    image: redis
    container_name: queuedb
    ports:
      - "6379:6379"
    networks:
      - appnet
    restart: always

  builder:
    build:
      context: apps/builder/
      dockerfile: Dockerfile
    container_name: builder
    networks:
      - appnet
    restart: always
    environment:
      - REDIS_URL=redis://queuedb:6379
      - REDIS_HOST=queuedb

# networks

networks:
  appnet:
    driver: bridge
